version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/blocklayerhq/chainkit
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Run linter
          command: make setup lint
      - run:
          name: Build
          command:
            make
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - persist_to_workspace:
          root: .
          paths:
            - chainkit

  integration-test:
    machine: true
    steps:
        - checkout
        - attach_workspace:
            at: /tmp/build
        - run: ./test/integration.sh /tmp/build/chainkit


workflows:
  version: 2
  build:
    jobs:
      - build
      - integration-test:
          requires:
            - build

