version: 2

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/blocklayerhq/chainkit
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Build
          command:
            go build
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/blocklayerhq/chainkit
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Run linter
          command: make setup check
      - run:
          name: Run unit tests
          command:
            go test -v ./...
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
